name: Integracion Continua

on: 
  push:
    branches: [ main ]

jobs: 
    ci_to_main: 
      runs-on: windows-2019
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 15.10.0
        - uses: actions/checkout@v2
        - uses: nanasess/setup-chromedriver@master
          with:
            chromedriver-version: '91.0.4472.101'
        - run: chromedriver --url-base=/wd/hub &
        - run: npm ci
        - run: npm test
        - run: npm run test:coverage
        - run: npm run executeHint
        - run: npm run atdd