name: Integracion Continua

on: 
  push:
    branches: [ main ]

jobs: 
  ci_to_main: 
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.16.1
      - run: npm ci
      - run: npm test