name: Integracion Continua

on: 
  push:
    branches: [ develop ]

jobs: 
    ci_to_main: 
      runs-on: windows-2019
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 15.10.0
        - name: Execute CI
          run: npm ci
        - name: Merge main
          run: npm run merge