name: Integracion Continua

on: 
  push:
    branches: [ develop ]

jobs: 
    ci_to_main: 
      runs-on: windows-2019
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 15.10.0
        - name: Execute CI
          run: npm ci
        - name: Execute Tests
          run: npm test
        - name: Execute Coverage 
          run: npm run test:coverage
        - name: Execute Static Analysis
          run: npm run executeHint
        - name: Merge main
          run: git checkout main 
          run: git merge develop
          run: git commit -m "Merge main"
          run: git push 